# Generated by Django 5.0.7 on 2024-07-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('bytes_recieved', models.BigIntegerField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
